Feature EE-885: Add Core Compatibility in Module Management window and create a process tu publish compatibility versions
etendosoftware/com.etendoerp.dependencymanager pull request #12
Opened 2024-05-06 15:34 UTC by tomyrodeghiero

2024-05-06 15:48 UTC, valenvivaldi requested changes

2024-05-06 15:48 UTC, valenvivaldi commented on src/com/etendoerp/dependencymanager/util/UpdateLocalPackagesUtil.java
>        processPackages(xmlRootElement);
the finally block with the "restorePreviousMode" is missing

2024-05-06 17:17 UTC, RomanMagnoli requested changes

2024-05-06 17:17 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_COLUMN.xml
AD_ELEMENTS are missing.

2024-05-06 17:17 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_MESSAGE.xml
> +<!--F1C801DEF21B489484BC830A0994156E-->  <MSGTYPE><![CDATA[I]]></MSGTYPE>
Shouldn't it be an error message?

2024-05-06 17:17 UTC, RomanMagnoli commented on src/com/etendoerp/dependencymanager/process/GetPackagesFromRepositories.java
> +        String[] parts = name.split("\\.");
Indentation.

2024-05-06 17:17 UTC, RomanMagnoli commented on src/com/etendoerp/dependencymanager/util/PackageUtil.java
> +      return packageVersions.get(0).getVersion();
setMaxResult and uniqueResult

2024-05-06 18:23 UTC, Gremiger commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--6F9FFCAF154B4EEBB9033BC83070C6D9-->  <NAME><![CDATA[Latest_Core]]></NAME>
```suggestion
<!--6F9FFCAF154B4EEBB9033BC83070C6D9-->  <NAME><![CDATA[Latest Core]]></NAME>
```

2024-05-06 18:23 UTC, Gremiger commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--70ED9EBA09CC45A2B174971B541B2D3A-->  <NAME><![CDATA[From_Core]]></NAME>
```suggestion
<!--70ED9EBA09CC45A2B174971B541B2D3A-->  <NAME><![CDATA[From Core]]></NAME>
```

2024-05-06 18:23 UTC, Gremiger commented on src-db/database/sourcedata/AD_MESSAGE.xml
> +<!--F1C801DEF21B489484BC830A0994156E-->  <MSGTYPE><![CDATA[I]]></MSGTYPE>
```suggestion
<!--F1C801DEF21B489484BC830A0994156E-->  <MSGTYPE><![CDATA[E]]></MSGTYPE>
```

2024-05-07 15:29 UTC, valenvivaldi requested changes

2024-05-07 15:29 UTC, valenvivaldi commented on src/com/etendoerp/dependencymanager/util/PackageUtil.java
> +    if (versionSplit.length != 2) throw new IllegalArgumentException(OBMessageUtils.messageBD("ETDEP_Invalid_Version_Range_Format") + versionRange);
its more safe the use of {} for the if then block

```suggestion
    if (versionSplit.length != 2){
     throw new IllegalArgumentException(OBMessageUtils.messageBD("ETDEP_Invalid_Version_Range_Format") + versionRange);

    }
```

2024-05-07 15:32 UTC, valenvivaldi commented on src/com/etendoerp/dependencymanager/process/GetPackagesFromRepositories.java
> +            throw new OBException("Redirected HTTP Request failed with status code: " + response.statusCode());
Message must be in AD_Message

2024-05-15 12:15 UTC, valeg-etendo requested changes

2024-05-15 12:15 UTC, valeg-etendo commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--6F9FFCAF154B4EEBB9033BC83070C6D9-->  <NAME><![CDATA[Latest_Core]]></NAME>
@tomyrodeghiero What is the purpose of this column? I have doubts about the chosen name

2024-05-15 12:15 UTC, valeg-etendo commented on src/com/etendoerp/dependencymanager/process/GetPackagesFromRepositories.java
>      private static final Logger log = LogManager.getLogger();
The formatting of this file is not correct. The indentation should be 2 and not 4. It would be convenient before merge the branch, to apply a formatting commit

2024-05-20 14:32 UTC, valenvivaldi approved these changes

2024-05-20 14:37 UTC, Gremiger commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--6F9FFCAF154B4EEBB9033BC83070C6D9-->  <NAME><![CDATA[Latest_Core]]></NAME>
😠

2024-05-20 14:40 UTC, RomanMagnoli requested changes

2024-05-20 14:40 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_MESSAGE.xml
> +<!--471949972AE74B9EB3A9BBA292A7D5B5-->  <MSGTYPE><![CDATA[I]]></MSGTYPE>
This message should be an error message

2024-05-20 14:40 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--6F9FFCAF154B4EEBB9033BC83070C6D9-->  <NAME><![CDATA[Latest_Core]]></NAME>
Latest_Core -> Latest Core

2024-05-20 14:40 UTC, RomanMagnoli commented on src/com/etendoerp/dependencymanager/util/PackageUtil.java
> +    List<PackageVersion> packageVersions = criteria.list();
???

Why are you setting a setMaxResults(1).uniqueResult() and after that you are using a list()??

2024-05-20 16:53 UTC, RomanMagnoli approved these changes

2024-05-20 19:58 UTC, Gremiger approved these changes

2024-05-29 17:04 UTC, RubenEtendo commented
@tomyrodeghiero check sonar issues. There's **35 code smells** arising from this new code

2024-05-29 17:05 UTC, RubenEtendo requested changes
@tomyrodeghiero check sonar issues. There's **35 code smells** arising from this new code

2024-05-30 05:51 UTC, isaiasb-etendo approved these changes

2024-06-04 12:56 UTC, valeg-etendo approved these changes

2024-06-04 16:30 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--6F9FFCAF154B4EEBB9033BC83070C6D9--><AD_COLUMN>
This column's application element does not have help nor description

2024-06-04 16:30 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--70ED9EBA09CC45A2B174971B541B2D3A--><AD_COLUMN>
This column's application element does not have help nor description

2024-06-04 19:32 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--C5C9F756972A43279420D98331C5CA1E-->  <POSITION><![CDATA[17]]></POSITION>
revert this chunk

2024-06-04 19:35 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/AddDependency.java
> +              PackageVersion latestPackageVersion = PackageUtil.getLastPackageVersion(packageVersion.getPackage());
check this change... the original line was 

`PackageVersion latestPackageVersion = PackageUtil.getLastPackageVersion(packageDependency.getDependencyVersion().getPackage());
`

And you change it.

2024-06-04 19:41 UTC, Matias-Bernal requested changes

2024-06-04 19:41 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/AddDependency.java
> +              OBMessageUtils.messageBD("ETDEP_Not_Dependencies"), packageVersion.getPackage().getIdentifier(),
This message doesn't exists, you must be more careful when resolve conflicts, because this was fixed in dev after your brach was created.

2024-06-05 06:59 UTC, isaiasb-etendo approved these changes

2024-06-05 07:02 UTC, merged