Feature EE-943: Improvements in change version process.
etendosoftware/com.etendoerp.dependencymanager pull request #13
Opened 2024-05-20 19:30 UTC by Matias-Bernal

EE-943

2024-05-21 10:48 UTC, RubenEtendo approved these changes

2024-05-21 11:20 UTC, tomyrodeghiero approved these changes

2024-05-21 11:23 UTC, tomyrodeghiero commented
@Matias-Bernal I approved the pull request; it has very clear code, but be careful because Sonar is not working. @valeg-etendo  shared this link with me: https://etendoproject.atlassian.net/wiki/spaces/KB/pages/2974121985/Configurar+pipeline+para+integrar+Code+Reviews+autom+ticas+y+SonarQube+en+Pull+Requests#Error%3A-Gradle-Project-detected, where it provides the change to fix it in your branch

2024-05-21 11:39 UTC, RubenEtendo commented
> @Matias-Bernal I approved the pull request; it has very clear code, but be careful because Sonar is not working. @valeg-etendo shared this link with me: https://etendoproject.atlassian.net/wiki/spaces/KB/pages/2974121985/Configurar+pipeline+para+integrar+Code+Reviews+autom+ticas+y+SonarQube+en+Pull+Requests#Error%3A-Gradle-Project-detected, where it provides the change to fix it in your branch

Hi everyone! @tomyrodeghiero @Matias-Bernal This is a relatively new error. It arised from some changes @valeg-etendo made in the sonar action. It will not be solved by any of the documented solutions. Its solution is to add the following code previous to the sonar pipe running in the action:

```
      ...
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
+    - name: Delete build.gradle (if exists)
+      run: |
+        if [ -f build.gradle ]; then
+          rm build.gradle
+          echo "'build.gradle' file deleted..."
+        fi
      - uses: sonarsource/sonarqube-scan-action@master
        env:
      ...
```

2024-05-21 11:42 UTC, tomyrodeghiero commented
> > @Matias-Bernal I approved the pull request; it has very clear code, but be careful because Sonar is not working. @valeg-etendo shared this link with me: https://etendoproject.atlassian.net/wiki/spaces/KB/pages/2974121985/Configurar+pipeline+para+integrar+Code+Reviews+autom+ticas+y+SonarQube+en+Pull+Requests#Error%3A-Gradle-Project-detected, where it provides the change to fix it in your branch
> 
> Hi everyone! @tomyrodeghiero @Matias-Bernal This is a relatively new error. It arised from some changes @valeg-etendo made in the sonar action. It will not be solved by any of the documented solutions. Its solution is to add the following code previous to the sonar pipe running in the action:
> 
> ```
>       ...
>       - uses: actions/checkout@v2
>         with:
>           fetch-depth: 0
> +    - name: Delete build.gradle (if exists)
> +      run: |
> +        if [ -f build.gradle ]; then
> +          rm build.gradle
> +          echo "'build.gradle' file deleted..."
> +        fi
>       - uses: sonarsource/sonarqube-scan-action@master
>         env:
>       ...
> ```

Hi @RubenEtendo! Thank you very much for your contribution, super clear!

2024-05-21 13:36 UTC, Gremiger commented on src/com/etendoerp/dependencymanager/filterexpression/ChangeFormatDefaultValuesExpression.java
@Matias-Bernal

2024-05-21 13:36 UTC, Gremiger commented on web/com.etendoerp.dependencymanager/js/changeVersionDropdown.js
@Matias-Bernal

2024-05-21 13:43 UTC, Gremiger commented on src-db/database/sourcedata/AD_ELEMENT.xml
@Matias-Bernal

2024-05-21 13:43 UTC, Gremiger commented on src-db/database/sourcedata/AD_ELEMENT.xml
@Matias-Bernal

2024-05-21 13:43 UTC, Gremiger commented on src/com/etendoerp/dependencymanager/process/ChangeVersion.java
@Matias-Bernal 

Does this bot comment make sense?

Suggestion:
The compareDependenciesForChange method call and the processDependencyChanges method call should be moved inside the if block where newVersion is not null. This ensures that these methods are only called when a new version is being set. [important]
Label:
possible issue
Existing code:
JSONArray dependenciesComparisonResults = compareDependenciesForChange(dependency.getGroup(),
    dependency.getArtifact(), currentVersion, updateToVersion);

processDependencyChanges(dependenciesComparisonResults);
Improved code:
if (!StringUtils.isEmpty(newVersionId) && !StringUtils.equals(newVersionId, "null")) {
    PackageVersion newVersion = OBDal.getInstance().get(PackageVersion.class, newVersionId);
    if (newVersion == null) {
        throw new OBException(OBMessageUtils.messageBD("ETDEP_Dependency_Not_Found_ID") + newVersionId);
    }
    log.debug("Changing version of dependency: {} to version ID: {}", dependency.getEntityName(), newVersionId);
    String currentVersion = dependency.getVersion();
    String updateToVersion = newVersion.getVersion();
    String latestVersion = InstallDependency.fetchLatestVersion(dependency.getGroup(), dependency.getArtifact());

    dependency.setVersion(updateToVersion);
    dependency.setInstallationStatus(PENDING);
    dependency.setVersionStatus(InstallDependency.determineVersionStatus(updateToVersion, latestVersion));

    JSONArray dependenciesComparisonResults = compareDependenciesForChange(dependency.getGroup(),
        dependency.getArtifact(), currentVersion, updateToVersion);

    processDependencyChanges(dependenciesComparisonResults);
}

2024-05-21 13:43 UTC, Gremiger commented on web/com.etendoerp.dependencymanager/js/changeVersionDropdown.js
> +        messageType = 'warning';
messageType should be `const`

2024-05-21 14:23 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/ChangeVersion.java
No

2024-05-24 17:38 UTC, valenvivaldi commented on src/com/etendoerp/dependencymanager/process/ChangeVersion.java
> +        if (StringUtils.isNotEmpty(externalVersion) && !StringUtils.equals(externalVersion, NULL_STRING)) {
check if you can use guard-clause

2024-05-24 17:39 UTC, valenvivaldi requested changes

2024-05-24 17:39 UTC, valenvivaldi commented on src/com/etendoerp/dependencymanager/filterexpression/DependencyManagerDefaultValuesExpression.java
> +            switch (context.getString("inpformat")) {
a switch inside another switchs can cause confusions. Extrat to a method

2024-05-28 13:43 UTC, valenvivaldi approved these changes

2024-05-28 13:54 UTC, RomanMagnoli approved these changes

2024-05-28 15:18 UTC, isaiasb-etendo approved these changes

2024-05-28 15:21 UTC, Gremiger approved these changes

2024-05-29 14:37 UTC, merged