Feature EE-886: Update packages from online dataset
etendosoftware/com.etendoerp.dependencymanager pull request #2
Opened 2024-04-08 18:51 UTC by sebastianbarrozo

2024-04-08 19:01 UTC, RubenEtendo requested changes

2024-04-08 19:01 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_MENU.xml
> +<!--028A6E33982145B7991CC38CF151577B-->  <ISSUMMARY><![CDATA[N]]></ISSUMMARY>
From now on, all new Application Dictionary elements should have a Description and Help to understand their motive

2024-04-08 19:01 UTC, RubenEtendo commented on src-db/database/sourcedata/OBUIAPP_PROCESS.xml
> +<!--3075F3E3862E459BB28102CE8F26C0DB-->  <ACCESSLEVEL><![CDATA[4]]></ACCESSLEVEL>
From now on, all new Application Dictionary elements should have a Description and Help to understand their motive

2024-04-08 20:32 UTC, RomanMagnoli approved these changes

2024-04-09 02:25 UTC, Gremiger approved these changes

2024-04-09 10:40 UTC, RubenEtendo approved these changes

2024-04-09 12:23 UTC, Tomas-Vesco requested changes

2024-04-09 12:23 UTC, Tomas-Vesco commented on src/com/etendoerp/dependencymanager/util/UpdateLocalPackagesUtil.java
>      // download DATASET_FILE_URL
Remove comment

2024-04-09 12:27 UTC, Tomas-Vesco requested changes

2024-04-09 12:27 UTC, Tomas-Vesco commented on src/com/etendoerp/dependencymanager/process/UpdatePackages.java
> +  private static final String BASIC_AUTH_TOKEN = "Basic ";
There is a space at the end, is that correct?

2024-04-09 12:32 UTC, Tomas-Vesco requested changes

2024-04-09 12:32 UTC, Tomas-Vesco commented on src/com/etendoerp/dependencymanager/actions/UpdateLocalPackagesAction.java
> +      // Package update successful
Remove comment

2024-04-09 12:34 UTC, Tomas-Vesco requested changes

2024-04-09 12:34 UTC, Tomas-Vesco commented on src/com/etendoerp/dependencymanager/utils/UpdateLocalPackagesUtil.java
> +import java.io.*;
Check if it is necessary to import everything

2024-04-09 18:12 UTC, Matias-Bernal approved these changes

2024-04-09 21:55 UTC, isaiasb-etendo approved these changes

2024-04-09 23:47 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/util/UpdateLocalPackagesUtil.java
> +import java.io.*;
remove it and add single format class import.

2024-04-09 23:53 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/actions/UpdateLocalPackagesAction.java
> +      return result;
unnecesary return

2024-04-09 23:53 UTC, Matias-Bernal approved these changes

2024-04-10 12:14 UTC, Tomas-Vesco approved these changes

2024-04-10 12:30 UTC, tomyrodeghiero approved these changes

2024-04-12 15:38 UTC, merged

2024-04-12 15:40 UTC, RubenEtendo commented
@sebastianbarrozo are the issues thrown by sonar false positives? if so, could you mark them as such in SonarQube?