Feature EE-1091: Process to obtain packages and commit
etendosoftware/com.etendoerp.dependencymanager pull request #26
Opened 2024-09-11 18:04 UTC by ivanrobledofutit

2024-09-17 16:54 UTC, jortolanosmf commented on src-test/src/com/etendoerp/dependencymanager/process/GetPackagesFromRepositoriesAndCommitTest.java
> +        assertEquals("Error", error.getType());
create an error variable for this string

2024-09-17 16:55 UTC, jortolanosmf requested changes
Check the comments

2024-09-17 23:29 UTC, Matias-Bernal requested changes

2024-09-17 23:29 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/util/git_operations.sh
> +        git push || { echo "Error: Could not push."; exit 1; }
Un test deberia dejar todo tal como lo encontro, por lo que este commit deberia borrarse del repo en esta rama.

2024-09-17 23:29 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/GetPackagesFromRepositoriesAndCommit.java
> +        String scriptToRun2 = "git_operations.sh";
Segun la documentacion de Etendo, este es compatible con Windows; ergo estamos seguros de que soporta estos .sh?

2024-10-01 13:30 UTC, Matias-Bernal approved these changes

2024-10-01 14:01 UTC, jortolanosmf approved these changes

2024-10-01 14:26 UTC, merged