Feature EE-835: Added Is Bundle check in Module Management window.
etendosoftware/com.etendoerp.dependencymanager pull request #4
Opened 2024-04-10 16:47 UTC by Matias-Bernal

2024-04-10 16:49 UTC, RomanMagnoli approved these changes

2024-04-10 17:01 UTC, RubenEtendo requested changes

2024-04-10 17:01 UTC, RubenEtendo commented on src-db/database/model/tables/ETDEP_PACKAGE.xml
> +        <onCreateDefault/>
For tables already populated with data, the creation of a new mandatory column should include a value set for it in the `onCreateDefault` property

2024-04-10 17:01 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--1926046ADA624DC3A0583378CF753147-->  <NAME><![CDATA[Is Bundle]]></NAME>
From now on, all new Application Dictionary entries need a description **and** help to better understand their motive

2024-04-10 19:33 UTC, sebastianbarrozo approved these changes

2024-04-11 11:38 UTC, RubenEtendo approved these changes

2024-04-11 11:38 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--1926046ADA624DC3A0583378CF753147-->  <DESCRIPTION><![CDATA[This field identified the modules that are bundles.]]></DESCRIPTION>
This field **identifies** the modules that are bundles.

2024-04-11 11:38 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--1926046ADA624DC3A0583378CF753147-->  <HELP><![CDATA[If this record has Is Bundle check marked then this module is a bundle.]]></HELP>
If this record has **the 'Is Bundle'** check marked, then this module is a bundle

2024-04-11 13:08 UTC, merged