Feature EE-853: Remove dependency version deletes & Add unit test
etendosoftware/com.etendoerp.dependencymanager pull request #5
Opened 2024-04-10 17:26 UTC by tomyrodeghiero

2024-04-10 17:31 UTC, tomyrodeghiero commented
> ![Failed](https://camo.githubusercontent.com/613137fb0c943ac9771c35e2c3cff4a50b8b65ac19860e69ca901004b1d1d0b4/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f5175616c6974794761746542616467652f6661696c65642e7376673f73616e6974697a653d74727565)
> 
> * 0.00% Coverage on New Code (is less than 80.00%)
> 
> # Analysis Details
> ## 12 Issues
> * ![Bug](https://camo.githubusercontent.com/5aa19ff3e73fdab8197696fb549ec35ca5c1df83c5c8a399f7eec2b2259b9a2c/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f6275672e7376673f73616e6974697a653d74727565) 0 Bugs
> * ![Vulnerability](https://camo.githubusercontent.com/d6a1abf092881417c5b8fb1a863cb3a10f824b7d34c80c73c15673b81ae3428b/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f76756c6e65726162696c6974792e7376673f73616e6974697a653d74727565) 0 Vulnerabilities
> * ![Code Smell](https://camo.githubusercontent.com/3a6b820399c90365cd849db4e7686d7c00e64d921209929d5b54b214507df40c/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f636f64655f736d656c6c2e7376673f73616e6974697a653d74727565) 12 Code Smells
> 
> ## Coverage and Duplications
> * ![Coverage](https://camo.githubusercontent.com/b0eb0fa19d1fcf2e7eb711417029cff109439a79f64c2e785fa659e2e8a39ad2/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f436f76657261676543686172742f302e7376673f73616e6974697a653d74727565) 0.00% Coverage (0.00% Estimated after merge)
> * ![Duplications](https://camo.githubusercontent.com/785b291f6fbc7e2a298393f4c3d6a8bbf73a2bb1a276efb617e93e59782f3bd4/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f4475706c69636174696f6e732f332e7376673f73616e6974697a653d74727565) 0.54% Duplicated Code (0.10% Estimated after merge)
> 
> **Project ID:** etendosoftware_com.etendoerp.dependencymanager_AY7CyzH9DY7wyJU_mHL7
> 
> [View in SonarQube](https://sonar.etendo.cloud/dashboard?id=etendosoftware_com.etendoerp.dependencymanager_AY7CyzH9DY7wyJU_mHL7&pullRequest=5)

The 12 code smells referred to using **var** instead of **const** or **let**, so I've marked all as resolved.

2024-04-10 19:31 UTC, Matias-Bernal approved these changes

2024-04-11 11:50 UTC, RubenEtendo requested changes
There are places where literals are being used instead of already defined constants in `ChangeVersion.java` and `SelectorChangeVersion.java` too

2024-04-11 11:50 UTC, RubenEtendo commented on src-test/src/com/etendoerp/dependencymanager/process/ChangeVersionTest.java
> +    assertEquals("group", result.getString("group"));
Use already defined constants in `PackageUtils`

2024-04-11 11:50 UTC, RubenEtendo commented on src-test/src/com/etendoerp/dependencymanager/process/ChangeVersionTest.java
> +    assertEquals("", result.getString("version_v1"));
Create constants for "version_v1" and "version_v2" literals

2024-04-11 12:24 UTC, RubenEtendo commented
> ![Failed](https://camo.githubusercontent.com/613137fb0c943ac9771c35e2c3cff4a50b8b65ac19860e69ca901004b1d1d0b4/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f5175616c6974794761746542616467652f6661696c65642e7376673f73616e6974697a653d74727565)
> 
> * 0.00% Coverage on New Code (is less than 80.00%)
> 
> # Analysis Details
> ## 1 Issue
> * ![Bug](https://camo.githubusercontent.com/5aa19ff3e73fdab8197696fb549ec35ca5c1df83c5c8a399f7eec2b2259b9a2c/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f6275672e7376673f73616e6974697a653d74727565) 0 Bugs
> * ![Vulnerability](https://camo.githubusercontent.com/d6a1abf092881417c5b8fb1a863cb3a10f824b7d34c80c73c15673b81ae3428b/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f76756c6e65726162696c6974792e7376673f73616e6974697a653d74727565) 0 Vulnerabilities
> * ![Code Smell](https://camo.githubusercontent.com/3a6b820399c90365cd849db4e7686d7c00e64d921209929d5b54b214507df40c/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636f6d6d6f6e2f636f64655f736d656c6c2e7376673f73616e6974697a653d74727565) 1 Code Smell
> 
> ## Coverage and Duplications
> * ![Coverage](https://camo.githubusercontent.com/b0eb0fa19d1fcf2e7eb711417029cff109439a79f64c2e785fa659e2e8a39ad2/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f436f76657261676543686172742f302e7376673f73616e6974697a653d74727565) 0.00% Coverage (0.00% Estimated after merge)
> * ![Duplications](https://camo.githubusercontent.com/785b291f6fbc7e2a298393f4c3d6a8bbf73a2bb1a276efb617e93e59782f3bd4/68747470733a2f2f736f6e61722e6574656e646f2e636c6f75642f7374617469632f636f6d6d756e6974794272616e6368506c7567696e2f636865636b732f4475706c69636174696f6e732f332e7376673f73616e6974697a653d74727565) 0.00% Duplicated Code (0.10% Estimated after merge)
> 
> **Project ID:** etendosoftware_com.etendoerp.dependencymanager_AY7CyzH9DY7wyJU_mHL7
> 
> [View in SonarQube](https://sonar.etendo.cloud/dashboard?id=etendosoftware_com.etendoerp.dependencymanager_AY7CyzH9DY7wyJU_mHL7&pullRequest=5)

This issue was just a 'use let or const' issue. I already marked it as 'won't fix'

2024-04-11 12:25 UTC, RubenEtendo commented on src-test/src/com/etendoerp/dependencymanager/process/ChangeVersionTest.java
> +    String key = PackageUtil.GROUP + ":" + PackageUtil.ARTIFACT;
Is it correct to join both the dependency group and artifact with ":"? Shouldn't it be "."?

2024-04-11 12:39 UTC, tomyrodeghiero commented on src-test/src/com/etendoerp/dependencymanager/process/ChangeVersionTest.java
> +    String key = PackageUtil.GROUP + ":" + PackageUtil.ARTIFACT;
> Is it correct to join both the dependency group and artifact with ":"? Shouldn't it be "."?

In the context of the method buildDependencyInfo provided, using a colon (":") to join both the dependency group and artifact is indeed correct. The method splits the key on ":", using the first part for the group and the second for the artifact. Here's how it's done:

```java
public JSONObject buildDependencyInfo(Map<String, PackageDependency> dependenciesCurrent, Map<String, PackageDependency> dependenciesUpdate, String key) throws JSONException {
    JSONObject dependencyInfo = new JSONObject();
    PackageDependency depV1 = dependenciesCurrent.get(key);
    PackageDependency depV2 = dependenciesUpdate.get(key);

    String[] parts = key.split(":");
    dependencyInfo.put(PackageUtil.GROUP, parts[0]);
    dependencyInfo.put(PackageUtil.ARTIFACT, parts[1]);
    dependencyInfo.put(PackageUtil.VERSION_V1, depV1 != null ? depV1.getVersion() : "");
    dependencyInfo.put(PackageUtil.VERSION_V2, depV2 != null ? depV2.getVersion() : "");

    if (depV1 == null && depV2 != null) {
      dependencyInfo.put(PackageUtil.STATUS, PackageUtil.NEW_DEPENDENCY);
    } else if (depV1 != null && depV2 != null && !StringUtils.equals(depV1.getVersion(), depV2.getVersion())) {
      dependencyInfo.put(PackageUtil.STATUS, PackageUtil.UPDATED);
    }

    return dependencyInfo;
}
```

So, the ":" is used intentionally and aligns with the method's logic for parsing dependency identifiers.

2024-04-11 12:51 UTC, RubenEtendo approved these changes

2024-04-11 13:19 UTC, merged