Feature EE-854: Add Local dependency type and add change format button
etendosoftware/com.etendoerp.dependencymanager pull request #6
Opened 2024-04-11 18:45 UTC by RubenEtendo

2024-04-11 20:09 UTC, tomyrodeghiero requested changes

2024-04-11 20:09 UTC, tomyrodeghiero commented on src/com/etendoerp/dependencymanager/DependencyManagerComponentProvider.java
> +    grhelper.addERP("changeFormat.js");
Consider using an array and a loop for cleaner and more maintainable code:

```java
public static final String[] JS_FILES = {
    "uninstallDependencyWarnings.js",
    "changeVersionDropdown.js",
    "changeFormat.js"
};

for (String file : jsFiles) {
    grhelper.addERP(file);
}
```

This approach simplifies adding multiple files and makes future updates easier

2024-04-11 20:09 UTC, tomyrodeghiero commented on src/com/etendoerp/dependencymanager/actions/ChangeFormat.java
> +        throw new OBException("Process is not Multi Records");
I think it's better take this to the AD_MESSAGE table

2024-04-11 20:09 UTC, tomyrodeghiero commented on src/com/etendoerp/dependencymanager/process/AddLocalDependencies.java
> +   * <p>
Is it correct that this paragraph tag is written?

2024-04-11 20:09 UTC, tomyrodeghiero commented on src/com/etendoerp/dependencymanager/process/AddLocalDependencies.java
> +              dep -> dep.getGroup() + "." + dep.getArtifact()) // Concatena los resultados de getGroup y getFormat para cada Dependency
Comment in Spanish, I admit that it has happened to me in the past haha

2024-04-11 20:13 UTC, tomyrodeghiero commented
@RubenEtendo The code overall looks great! I have let a few comments that would be good to address. It's also good to know that the pull request doesn't have any Sonar errors

2024-04-11 22:59 UTC, Matias-Bernal commented on src-db/database/model/tables/ETDEP_DEPENDENCY.xml
> +        <onCreateDefault><![CDATA['N']]></onCreateDefault>
Remove single quotes

2024-04-11 23:00 UTC, Matias-Bernal commented on src-db/database/model/tables/ETDEP_DEPENDENCY.xml
>          <onCreateDefault><![CDATA['N']]></onCreateDefault>
Remove single quotes

2024-04-11 23:00 UTC, Matias-Bernal commented on src-db/database/model/tables/ETDEP_DEPENDENCY.xml
> +        <onCreateDefault><![CDATA['PENDING']]></onCreateDefault>
Remove single quotes

2024-04-11 23:01 UTC, Matias-Bernal commented on src-db/database/model/tables/ETDEP_DEPENDENCY.xml
> -      <check name="ETD_CHK_CV"><![CDATA[CHANGE_VERSION IN ('Y', 'N')]]></check>
Revert this.

2024-04-11 23:02 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--5C20BFC54EF24D0F80AE4C91FC6BE1D7-->  <PRINTNAME><![CDATA[New Format]]></PRINTNAME>
add description and help

2024-04-11 23:14 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/actions/ChangeFormat.java
> +  int errors = 0;
Consider use this variable as method variable

2024-04-11 23:21 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/eventhandler/InstallationStatusEventHandler.java
> +    Dependency dependency = (Dependency) event.getTargetInstance();
Move this to new method to get a Dependency object.

2024-04-11 23:22 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/filterexpression/ChangeFormatDefaultValuesExpression.java
> +      if (currentParam != null && StringUtils.equals(currentParam, "newFormat")) {
StringUtils. equals  check if currentParam is null.

2024-04-11 23:24 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/AddLocalDependencies.java
> +          File xmlFile = new File(dir, "src-db/database/sourcedata/AD_MODULE.xml");
Invalid path in some environments

2024-04-11 23:25 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/process/AddLocalDependencies.java
> +      String modulesCorePath = OBPropertiesProvider.getInstance().getOpenbravoProperties().getProperty(
Invalid path in some environments

2024-04-11 23:31 UTC, Matias-Bernal commented on src/com/etendoerp/dependencymanager/util/DependencyUtil.java
> +    String sourceDepFilePath = sourceRootPath + "/modules/" + dependencyName;
Invalid path in some environments

2024-04-16 13:49 UTC, RubenEtendo commented on src-db/database/sourcedata/OBUISEL_SELECTOR_FIELD.xml
>  <?xml version='1.0' encoding='UTF-8'?>
This file was uploaded without format from another issue. It appeared to me after I exported my database changes, so I uploaded it in this

2024-04-16 14:30 UTC, Matias-Bernal approved these changes

2024-04-16 14:39 UTC, Gremiger approved these changes

2024-04-16 18:05 UTC, RomanMagnoli approved these changes

2024-04-17 11:17 UTC, tomyrodeghiero approved these changes

2024-04-18 11:16 UTC, valenvivaldi approved these changes

2024-04-23 13:46 UTC, Matias-Bernal commented on src-db/database/model/tables/ETDEP_DEPENDENCY.xml
> +        <onCreateDefault/>
For tables already populated with data, the creation of a new mandatory column should include a value set for it in the onCreateDefault property

2024-04-23 13:48 UTC, Matias-Bernal commented on src-db/database/sourcedata/AD_MENU.xml
> +<!--4AFE123C98784EFF87716853EE91ED75-->  <NAME><![CDATA[Module Management ]]></NAME>
Remove unnecessary spaces

2024-04-23 13:49 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_MESSAGE.xml
> +<!--0EF02C812F3A429687133C70F4D967FF-->  <MSGTYPE><![CDATA[E]]></MSGTYPE>
Is it correct for this message to be an error?

2024-04-23 13:49 UTC, RomanMagnoli commented on src-db/database/sourcedata/AD_MENU.xml
> +<!--4AFE123C98784EFF87716853EE91ED75-->  <NAME><![CDATA[Module Management ]]></NAME>
Blank space at the end.

2024-04-23 13:50 UTC, Matias-Bernal approved these changes

2024-04-26 17:21 UTC, valeg-etendo approved these changes

2024-04-30 19:15 UTC, Matias-Bernal approved these changes

2024-04-30 19:30 UTC, merged