Feature EE-835: Fixed is external dependecy check.
etendosoftware/com.etendoerp.dependencymanager pull request #8
Opened 2024-04-22 20:53 UTC by Matias-Bernal

2024-04-23 11:19 UTC, RubenEtendo requested changes

2024-04-23 11:19 UTC, RubenEtendo commented on src-db/database/model/tables/ETDEP_PACKAGE_DEP.xml
>          <onCreateDefault/>
Añadir valor en `onCreateDefault`

2024-04-23 11:19 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_COLUMN.xml
> +<!--53271001353E44A0A04168C9276E2FFC-->  <COLUMNNAME><![CDATA[isexternal_dependency]]></COLUMNNAME>
Maybe it should be `isexternaldependency`? I put it like that in my issue branch :grimacing:

2024-04-23 11:19 UTC, RubenEtendo commented on src-db/database/sourcedata/AD_ELEMENT.xml
> +<!--68B51A8E4A434C0E8D6ABAB8DF959DAA-->  <COLUMNNAME><![CDATA[isexternal_dependency]]></COLUMNNAME>
Same as commented above

2024-04-23 14:00 UTC, Gremiger commented
Look at Ruben comments. Otherwise, LGTM

2024-04-23 14:00 UTC, Gremiger approved these changes

2024-04-23 14:14 UTC, RomanMagnoli approved these changes

2024-04-25 12:15 UTC, valenvivaldi approved these changes
check @RubenEtendo comments

2024-04-25 12:20 UTC, RubenEtendo approved these changes

2024-04-25 12:35 UTC, tomyrodeghiero approved these changes

2024-04-30 19:36 UTC, merged